[package]
name = "lzfse_sys"
version = "0.1.0"
authors = ["Vin Singh Ghataore <theshampoofactory@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
links = "lzfse"

[dependencies]
libc = "0.2.88"